# Generated by Django 5.2.6 on 2025-09-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0002_cliente_cpf_cnpj_cliente_email_cliente_ie_rg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='titulo',
            new_name='nome_categoria',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='titulo',
            new_name='nome_do_produto',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='garantia',
            new_name='praso_para_devolucao',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='returm_devolucao',
            new_name='prazo_para_garantia',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='preco_mercado',
            new_name='preco_de_mercado',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='venda',
            new_name='preco_de_venda',
        ),
    ]
