# Generated by Django 5.2.6 on 2025-09-29 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lojaapp', '0003_rename_titulo_categoria_nome_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='nome_categoria',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='praso_para_devolucao',
            new_name='devolucao',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='prazo_para_garantia',
            new_name='garantia',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='preco_de_mercado',
            new_name='mercado',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='nome_do_produto',
            new_name='titulo',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='preco_de_venda',
            new_name='venda',
        ),
    ]
